Add uploading and copy download command
dutchcoders/transfer.sh pull request #412
Opened 2021-09-17 10:44 UTC by GanZhiXiong

2021-10-03 13:49 UTC, aspacca requested changes

2021-10-03 13:49 UTC, aspacca commented on examples.md
> +It was designed for 🐧 Linux or 🍎 macOS.
please, remove emoji :)

2021-11-08 18:30 UTC, aspacca commented
closing the PR since no feedback

2021-11-09 04:40 UTC, GanZhiXiong commented
@aspacca 
I'm sorry. I just saw the news.

Can you reopen this PR? I will solve the problem as requested immediately.
Thanks!

2021-11-13 08:16 UTC, merged