allow range request for every content type, move lock only when metad…
dutchcoders/transfer.sh pull request #495
Opened 2022-07-10 04:51 UTC by aspacca

…ata has to be updated

2022-07-10 04:54 UTC, aspacca commented
related to #409 

see https://github.com/dutchcoders/transfer.sh/issues/490#issuecomment-1179545800 and https://github.com/dutchcoders/transfer.sh/issues/490#issuecomment-1179654566  


@stefanbenten can you take a look when you have time?

this is to add the support on `transfer.sh` service, hosted instances like https://transfer.sh might require tuninque eventual proxy on top of the service

2022-07-10 11:04 UTC, stefanbenten requested changes
This needs a lot more work to do proper range requests without having to download the entire file. I have been trying to plumb the range requests through to the backend and let it handle it accordingly. Tho this either requires a change of the backend storage interface or creating lots logic and temporary files from within the storage provider (google storage being the only one tho).

2022-07-10 11:04 UTC, stefanbenten commented on server/handlers.go
> +	if r.Header.Get("Range") != "" {
This creates a very big amount of unnecessary downloads of the entire file and thus lots of load on the backend storage (for cases of remote storage via full downloads and for local storage due to copying the file entirely into a temp file) in L1078.

2022-07-10 11:05 UTC, stefanbenten commented
Let me see, if i can push this PR sometime today..

2022-07-10 11:19 UTC, aspacca commented on server/handlers.go
> +	if r.Header.Get("Range") != "" {
it just creates them for every type of file content instead of video and audio files
where was a bug (`w` vs `r`) in the original implementation that prevented range requests to be fulfilled on non audio/video files

but yes, we should try to exploit range donwload directly from the storage implementation.
we can change the `storage.Get` interface to receive the range to pass down to the concrete storage "sdk" in order to minimise what's actually downloaded

good catch anyway: mine was a quick hack and I didn't think about the performance implications

2023-03-01 14:26 UTC, aspacca commented
closed in favor of #527 

we still should keep https://github.com/dutchcoders/transfer.sh/pull/495/files#diff-961509ed3ff668f3172148150903514fb3394d6ff090d6db78d986875b13689fR705-R706, for donwloaders that send multiple concurrent range request

2023-03-01 14:26 UTC, closed without merging